### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Valentiino** [TKGP/STALK-IRC#2]
With logs like these

[error]Expression : !m_error_code
[error]Function : raii_guard::~raii_guard
[error]File : D:\prog_repository\sources\trunk\xrServerEntities\script_storage.cpp
[error]Line : 748
[error]Description : \gamedata\scripts\stalk_irc.script:87: attempt to index local 'gameIcon' (a nil value)

Fixed by restarting the client, replicates itself over time

**Comment by TKGP** [comment]
Fixed in Beta 12.
