### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by AequusMihi** [TKGP/STALK-IRC#3]
![capture](https://cloud.githubusercontent.com/assets/11820493/7007233/9faf402c-dc90-11e4-988b-b7d3900049d7.PNG)
This happens everytime when I try to launch it.
I have Win7 64bit and installed .NET versions 4.5.2 and 4.5.3

**Comment by TKGP** [comment]
Fixed in 990a88e80045dd459d2acf29964dc70d11063ee1
